modLoader = "javafml"
loaderVersion = "[46,)"
license = "MIT"
[[mods]]
    modId = "compatwatchdog"
    version = "${version}"
    displayName = "CompatWatchDog"
    description = ""

[[dependencies.compatwatchdog]]
    modId = "forge"
    mandatory = true
    versionRange = "[46,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.compatwatchdog]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20,)"
    ordering = "NONE"
    side = "BOTH"

[modproperties.compatwatchdog]
    'compatwatchdog:compats' = [
        { type="mod", id="resourcefullib" }
    ]
